# This is a basic workflow to help you get started with Actions

name: Flutter Runner

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: veerajs/flutter-0.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master

    - name: clean stale build and cache
      run: flutter clean

    - name: install dependencies
      run: flutter pub get

    - name: build apk
      run: flutter build apk
